### ISSUE TITLE
immediateCleanupOn: Failure not working

### ISSUE THREAD

**Issue by mudverma** [IBM/kubernetes-driver#40]
We have a resource helm that we want to remove upon Failures.  [As per the docs](https://github.com/IBM/kubernetes-driver/blob/b84cdd4358914674de40154da3084142c8e2923d/docs/user-guide/building-a-resource.md#remove-immediately)  we have defined the following keg.yaml 

We want the resource to be removed when there is a failure in transition/operation. Therefore, we have included - immediateCleanupOn: Failure 

```
compose:
  - name: Create
    deploy:
      - helm:
          chart: "{{ componentName }}-{{ siteName }}-{{ softwareVersion }}-{{ helmTag }}.tgz"
          name: "r{{ componentName }}-{{ system_properties.resource_id_label | truncate(8,true,'') }}"
          namespace: "{{ resourceNamespace }}"
          values: "values-{{ componentName }}-{{ siteName }}-{{ softwareVersion }}-{{ helmTag }}.yaml"
        immediateCleanupOn: Failure
    checkReady:
      script: check-validation.py
      maxAttempts: 5
      timeoutSeconds: 200
      intervalSeconds: 40
```

But when checkReady fails, or on install failure,  helm chart and corresponding resources are not removed.  Are we missing something?  Is this the expected behavior? 

In the below example, for one resource, the readiness check has failed (because pods failed to come up fine), therefore, we want to clean up the helm chart and delete it. 

<img width="1017" alt="Screenshot 2021-05-27 at 11 35 02 AM" src="https://user-images.githubusercontent.com/4323340/119774297-957e5100-bedf-11eb-8948-e59a306bb26a.png">
