### ISSUE TITLE
Allow name and content of readyCheck script to be templated

### ISSUE THREAD

**Issue by dvaccarosenna** [IBM/kubernetes-driver#46]
Add support for dynamic value population in check ready script and it's name.

```
compose:
  - name: Create
    deploy:
      - helm:
          chart: apache-7.3.15.tgz
          name: r{{ system_properties.resource_id_label }}
          namespace: default
          values: "apache-helm-chart-values.yaml"
    checkReady:
      script: "{{ nameCheck }}.py"
```

Content of the `{{ nameCheck }}.py` to also be rendered as a template.
